### PR TITLE
Add boilerplate files

### PR DESCRIPTION
**Pull request by morrisallison**

### CODE REVIEW

**Comment by LionOps** [comment]
:+1: 

After this lands...
- Enable Travis on both Travis and Github side
- Merge master into the other PR.

**Comment by LionOps** [comment]
We need a copy of the license, else @stefanor will be the saddest person you've ever sat next to in an office environment.

**Comment by stefanor** [comment]
Thanks @DevShep :)

**Comment by morrisallison** [comment]
The license is already in master

**Comment by morrisallison** [comment]
and I don't have the permissions to enable Travis on this repo.

**Comment by stefanor** [comment]
but I've enabled it.

**Pull request merged**
